### ISSUE TITLE
RuntimeError: 

### ISSUE THREAD

**Issue by huahuahauhau** [liurunsmileliu/yolov5_deepsort_fish#1]
我在运行的时候，提示问题RuntimeError: Error(s) in loading state_dict for Net: size mismatch for classifier.4.weight: copying a param with shape torch.Size([751, 256]) from checkpoint, the shape in current model is torch.Size([1, 256]). size mismatch for classifier.4.bias: copying a param with shape torch.Size([751]) from checkpoint, the shape in current model is torch.Size([1]).
 
如果大家出现这样的情况，应该是匹配问题。我换了一个官网下的yolov5模型就解决了。
这个问题折磨了我一下午

**Comment by liurunsmileliu** [comment]
我用的是自己训练之后的best.pt，如需训练自己的数据，修改成yolov5官方文件即可
